### ISSUE TITLE
Prize definition discussion

### ISSUE THREAD

**Issue by ngdevc** [IvanAdmaers/react-roulette-pro#9] opened 2022-06-23 15:03 UTC
https://user-images.githubusercontent.com/65579678/175330717-7c1cef2b-74a6-469f-9fdb-9a413749c648.mp4

**Comment by IvanAdmaers** [comment] 2022-06-23 17:25
Hello, @tortu. Does this happen when the prize item index changes?

**Comment by ngdevc** [comment] 2022-06-23 18:38
import React, { useContext, useEffect, useMemo, useState } from 'react'
import classNames from 'classnames'
import RoulettePro from 'react-roulette-pro';
import 'react-roulette-pro/dist/index.css';

import styles from './styles.module.scss'
import AudioPlayer from '../../Shared/AudioPlayer';
import { ImgPinBottom, ImgPinTop } from '../../../constants/images'
import { numberList } from '../../../constants/numbers'
import { AudioRolling } from '../../../constants/audios';
import { getPrizeIndex } from '../../../utils/handleRouletteSpinner'
import { AppContext } from '../../../providers/AppProvider'

const RouletteSpinner = ({endRoll}) => {
  const [start, setStart] = useState(false);
  const [prizeIndex, setPrizeIndex] = useState(10);
  const { isJoinedRound, isRolling } = useContext(AppContext);
  const [isFirstRender, setIsFirstRender] = useState(true);
  const spinning = useMemo(() => isRolling, [isRolling]);

  const handlePrizeDefined = () => {
    if (isFirstRender) setIsFirstRender(false);
    else {
      endRoll({
        index: prizeIndex, 
        color: numberList[prizeIndex].color,
        img: numberList[prizeIndex].img,
        created_at: new Date().toLocaleTimeString()
      });
    }
  };

  useEffect(() => {
    if (prizeIndex && !start) setStart(true);
  }, [prizeIndex, start]);

  useEffect(() => {
    if (!spinning) return;

    const prepare = async () => {
      const newPrizeIndex = await getPrizeIndex();

      setPrizeIndex(newPrizeIndex);
      setStart(false);
    };

    prepare();
  }, [spinning]); 

  return (
    
    <div className={classNames('position-relative', styles.roulette_spinner)}>
      <div className={styles.mask_left}></div>
      <AudioPlayer src={AudioRolling} playing={spinning && isJoinedRound} />
      <RoulettePro
        design='Regular'
        prizes={numberList}
        prizeIndex={prizeIndex}
        spinningTime={11}
        start={start}
        onPrizeDefined={handlePrizeDefined}
        topChildren={<img src={ImgPinTop} alt='Pin top image'/>}
        bottomChildren={<img src={ImgPinBottom} alt='Pin bottom image'/>}
        options={{stopInCenter: true}}
        designOptions={{
          hideCenterDelimiter: true,
          withoutAnimation: true,
          prizeItemWidth: 70,
        }}
        prizeItemRenderFunction={(props, index) => (
          <li key={props.color + index}>
            <img src={props.img} width='70px' alt='Number image'/>
          </li>
        )}
      />
      <div className={styles.mask_right}></div>
    </div>
  )
}
export default RouletteSpinner

**Comment by ngdevc** [comment] 2022-06-23 18:38
This is the roulette component.
The prize item index  is changed always to the index picked in last round.

**Comment by IvanAdmaers** [comment] 2022-06-23 21:26
Ok I’ll check it tomorrow

**Comment by IvanAdmaers** [comment] 2022-06-24 08:16
Hi. I checked your code. Here's the explanation of the behavior - https://github.com/IvanAdmaers/react-roulette-pro/issues/8#issuecomment-1158942380

**Comment by ngdevc** [comment] 2022-06-24 15:57
Helo, @IvanAdmaers 
It's not helped to solve this issue. As you can see thorugh this screen, if the pcked index is smaller than the previous index, direction moves in the opposite direction. 
And if the difference between current index and previous index is big the roulette move quickly, but if not, it move so slowly.
![image](https://user-images.githubusercontent.com/65579678/175572180-47af3b61-54ce-4618-bc5f-b3c956fb8686.png)

**Comment by ngdevc** [comment] 2022-06-24 16:13
Please check this video so that you can know the roulette works incorrectly.
https://user-images.githubusercontent.com/65579678/175575296-6abb82b4-133a-47d2-a185-e2871a384483.mp4

**Comment by IvanAdmaers** [comment] 2022-06-24 17:46
﻿﻿Behaviours you described are correct. Problems might be due to different ways of setting ‘prizeIndex’. I’d like to suggest you to take a look on this code from the live example - https://github.com/IvanAdmaers/react-roulette-pro/blob/main/example/src/App.js and try to set ‘prizeIndex’ similarly

**Comment by ngdevc** [comment] 2022-06-27 18:24
I tried to solve it, But no progress.
Could you help me through anydesk or teamview?

**Comment by ngdevc** [comment] 2022-06-27 19:44
I"m really not sure if this issue should be solved on my side or not.

**Comment by IvanAdmaers** [comment] 2022-06-28 05:45
You can share the logic of defining prizes and I'll try to help you

**Comment by ngdevc** [comment] 2022-07-05 10:03
@IvanAdmaers 
in this app, roulette spin runs automatically for each 15s.
but If I inactive this tab before roulette is started and active this tab after roulette is started, direction moves in the opposite direction or moves slowly.

https://user-images.githubusercontent.com/65579678/177303123-05362587-0c41-4bd8-bbad-0d0ad7785f11.mp4

**Comment by IvanAdmaers** [comment] 2022-07-05 13:00
Could you tell me please, does this happen only if your tab is inactive?

**Comment by ngdevc** [comment] 2022-07-06 01:18
Yes,

**Comment by IvanAdmaers** [comment] 2022-07-06 06:13
I was trying to reproduce this bug in the [live example](https://react-roulette-pro.ivanadmaers.com/) but it works correctly. Can you share your current roulette component code?

https://user-images.githubusercontent.com/66776981/177481170-5cfb195d-b648-4138-90ee-0fd864e229ae.mp4

**Comment by tortuc** [comment] 2022-07-06 15:00
`import React, { useEffect, useState } from 'react'
import classNames from 'classnames'
import { useSelector } from 'react-redux';
import RoulettePro from 'react-roulette-pro';
import 'react-roulette-pro/dist/index.css';

import styles from './styles.module.scss'
import { AudioPlayer } from '../../Shared';
import { ImgPinBottom, ImgPinTop } from '../../../constants/images'
import { numberList } from '../../../constants/numbers'
import { AudioRolling } from '../../../constants/audios';
import { getPrizeIndex } from '../../../utils/handleRouletteSpinner'
import { getIsRolling } from '../../../store/global/selectors'

const RouletteSpinner = ({endRoll}) => {
  const isRolling = useSelector(getIsRolling);

  const [playing, setPlaying] = useState(false);
  const [start, setStart] = useState(false);
  const [prizeIndex, setPrizeIndex] = useState(67);
  const [isFirstRender, setIsFirstRender] = useState(true);

  const handlePrizeDefined = () => {
    if (isFirstRender) {
      setIsFirstRender(false);
    }
    else {
      endRoll({
        index: prizeIndex, 
        color: numberList[prizeIndex].color,
        img: numberList[prizeIndex].img,
        created_at: new Date().toLocaleTimeString()
      });
    }
  };

  useEffect(() => {
    if (prizeIndex && !start) setStart(true);
    if (start && !isFirstRender) setPlaying(true);
  }, [prizeIndex, start]);

  useEffect(() => {
    if (!isRolling) return;

    const prepare = async () => {
      const newPrizeIndex = await getPrizeIndex();

      setPrizeIndex(prev => prev === newPrizeIndex ? newPrizeIndex -1 : newPrizeIndex);
      setStart(false);
    };

    prepare();
  }, [isRolling]); 

  return (
    
    <div className={classNames('position-relative', styles.roulette_spinner)}>
      <div className={styles.mask_left}></div>
      <AudioPlayer src={AudioRolling} playing={playing} onEnded={() => setPlaying(false)}/>
      <RoulettePro
        design='Regular'
        prizes={numberList}
        prizeIndex={prizeIndex}
        spinningTime={10.1}
        start={start}
        onPrizeDefined={handlePrizeDefined}
        topChildren={<img className={styles.pin_top} src={ImgPinTop} alt='Pin top image'/>}
        bottomChildren={<img className={styles.pin_bottom} src={ImgPinBottom} alt='Pin bottom image'/>}
        options={{stopInCenter: true}}
        designOptions={{
          hideCenterDelimiter: true,
          withoutAnimation: true,
          prizeItemWidth: 80,
        }}
        prizeItemRenderFunction={(props, index) => (
          <li key={props.color + index}>
            <img className={styles.number_item}  src={props.img} width='74px' alt='Number image'/>
          </li>
        )}
      />
      <div className={styles.mask_right}></div>
    </div>
  )
}
export default RouletteSpinner`

**Comment by tortuc** [comment] 2022-07-06 15:01
import React, { useEffect, useState } from 'react'
import classNames from 'classnames'
import { useSelector } from 'react-redux';
import RoulettePro from 'react-roulette-pro';
import 'react-roulette-pro/dist/index.css';

import styles from './styles.module.scss'
import { AudioPlayer } from '../../Shared';
import { ImgPinBottom, ImgPinTop } from '../../../constants/images'
import { numberList } from '../../../constants/numbers'
import { AudioRolling } from '../../../constants/audios';
import { getPrizeIndex } from '../../../utils/handleRouletteSpinner'
import { getIsRolling } from '../../../store/global/selectors'

const RouletteSpinner = ({endRoll}) => {
  const isRolling = useSelector(getIsRolling);

  const [playing, setPlaying] = useState(false);
  const [start, setStart] = useState(false);
  const [prizeIndex, setPrizeIndex] = useState(67);
  const [isFirstRender, setIsFirstRender] = useState(true);

  const handlePrizeDefined = () => {
    if (isFirstRender) {
      setIsFirstRender(false);
    }
    else {
      endRoll({
        index: prizeIndex, 
        color: numberList[prizeIndex].color,
        img: numberList[prizeIndex].img,
        created_at: new Date().toLocaleTimeString()
      });
    }
  };

  useEffect(() => {
    if (prizeIndex && !start) setStart(true);
    if (start && !isFirstRender) setPlaying(true);
  }, [prizeIndex, start]);

  useEffect(() => {
    if (!isRolling) return;

    const prepare = async () => {
      const newPrizeIndex = await getPrizeIndex();

      setPrizeIndex(prev => prev === newPrizeIndex ? newPrizeIndex -1 : newPrizeIndex);
      setStart(false);
    };

    prepare();
  }, [isRolling]); 

  return (
    
    <div className={classNames('position-relative', styles.roulette_spinner)}>
      <div className={styles.mask_left}></div>
      <AudioPlayer src={AudioRolling} playing={playing} onEnded={() => setPlaying(false)}/>
      <RoulettePro
        design='Regular'
        prizes={numberList}
        prizeIndex={prizeIndex}
        spinningTime={10.1}
        start={start}
        onPrizeDefined={handlePrizeDefined}
        topChildren={<img className={styles.pin_top} src={ImgPinTop} alt='Pin top image'/>}
        bottomChildren={<img className={styles.pin_bottom} src={ImgPinBottom} alt='Pin bottom image'/>}
        options={{stopInCenter: true}}
        designOptions={{
          hideCenterDelimiter: true,
          withoutAnimation: true,
          prizeItemWidth: 80,
        }}
        prizeItemRenderFunction={(props, index) => (
          <li key={props.color + index}>
            <img className={styles.number_item}  src={props.img} width='74px' alt='Number image'/>
          </li>
        )}
      />
      <div className={styles.mask_right}></div>
    </div>
  )
}
export default RouletteSpinner

**Comment by tortuc** [comment] 2022-07-06 15:02
`
import React, { useEffect, useState } from 'react'
import classNames from 'classnames'
import { useSelector } from 'react-redux';
import RoulettePro from 'react-roulette-pro';
import 'react-roulette-pro/dist/index.css';

import styles from './styles.module.scss'
import { AudioPlayer } from '../../Shared';
import { ImgPinBottom, ImgPinTop } from '../../../constants/images'
import { numberList } from '../../../constants/numbers'
import { AudioRolling } from '../../../constants/audios';
import { getPrizeIndex } from '../../../utils/handleRouletteSpinner'
import { getIsRolling } from '../../../store/global/selectors'
`
`
const RouletteSpinner = ({endRoll}) => {
  const isRolling = useSelector(getIsRolling);

  const [playing, setPlaying] = useState(false);
  const [start, setStart] = useState(false);
  const [prizeIndex, setPrizeIndex] = useState(67);
  const [isFirstRender, setIsFirstRender] = useState(true);

  const handlePrizeDefined = () => {
    if (isFirstRender) {
      setIsFirstRender(false);
    }
    else {
      endRoll({
        index: prizeIndex, 
        color: numberList[prizeIndex].color,
        img: numberList[prizeIndex].img,
        created_at: new Date().toLocaleTimeString()
      });
    }
  };

  useEffect(() => {
    if (prizeIndex && !start) setStart(true);
    if (start && !isFirstRender) setPlaying(true);
  }, [prizeIndex, start]);

  useEffect(() => {
    if (!isRolling) return;

    const prepare = async () => {
      const newPrizeIndex = await getPrizeIndex();

      setPrizeIndex(prev => prev === newPrizeIndex ? newPrizeIndex -1 : newPrizeIndex);
      setStart(false);
    };

    prepare();
  }, [isRolling]); 

  return (
    
    <div className={classNames('position-relative', styles.roulette_spinner)}>
      <div className={styles.mask_left}></div>
      <AudioPlayer src={AudioRolling} playing={playing} onEnded={() => setPlaying(false)}/>
      <RoulettePro
        design='Regular'
        prizes={numberList}
        prizeIndex={prizeIndex}
        spinningTime={10.1}
        start={start}
        onPrizeDefined={handlePrizeDefined}
        topChildren={<img className={styles.pin_top} src={ImgPinTop} alt='Pin top image'/>}
        bottomChildren={<img className={styles.pin_bottom} src={ImgPinBottom} alt='Pin bottom image'/>}
        options={{stopInCenter: true}}
        designOptions={{
          hideCenterDelimiter: true,
          withoutAnimation: true,
          prizeItemWidth: 80,
        }}
        prizeItemRenderFunction={(props, index) => (
          <li key={props.color + index}>
            <img className={styles.number_item}  src={props.img} width='74px' alt='Number image'/>
          </li>
        )}
      />
      <div className={styles.mask_right}></div>
    </div>
  )
}
export default RouletteSpinner
`

**Comment by ngdevc** [comment] 2022-07-06 15:04
![image](https://user-images.githubusercontent.com/65579678/177582999-322b784c-764a-44a3-a178-d943b3990b60.png)


```
import React, { useEffect, useState } from 'react'
import classNames from 'classnames'
import { useSelector } from 'react-redux';
import RoulettePro from 'react-roulette-pro';
import 'react-roulette-pro/dist/index.css';

import styles from './styles.module.scss'
import { AudioPlayer } from '../../Shared';
import { ImgPinBottom, ImgPinTop } from '../../../constants/images'
import { numberList } from '../../../constants/numbers'
import { AudioRolling } from '../../../constants/audios';
import { getPrizeIndex } from '../../../utils/handleRouletteSpinner'
import { getIsRolling } from '../../../store/global/selectors'

const RouletteSpinner = ({endRoll}) => {
  const isRolling = useSelector(getIsRolling);

  const [playing, setPlaying] = useState(false);
  const [start, setStart] = useState(false);
  const [prizeIndex, setPrizeIndex] = useState(67);
  const [isFirstRender, setIsFirstRender] = useState(true);

  const handlePrizeDefined = () => {
    if (isFirstRender) {
      setIsFirstRender(false);
    }
    else {
      endRoll({
        index: prizeIndex, 
        color: numberList[prizeIndex].color,
        img: numberList[prizeIndex].img,
        created_at: new Date().toLocaleTimeString()
      });
    }
  };

  useEffect(() => {
    if (prizeIndex && !start) setStart(true);
    if (start && !isFirstRender) setPlaying(true);
  }, [prizeIndex, start]);

  useEffect(() => {
    if (!isRolling) return;

    const prepare = async () => {
      const newPrizeIndex = await getPrizeIndex();

      setPrizeIndex(prev => prev === newPrizeIndex ? newPrizeIndex -1 : newPrizeIndex);
      setStart(false);
    };

    prepare();
  }, [isRolling]); 

  return (
    
    <div className={classNames('position-relative', styles.roulette_spinner)}>
      <div className={styles.mask_left}></div>
      <AudioPlayer src={AudioRolling} playing={playing} onEnded={() => setPlaying(false)}/>
      <RoulettePro
        design='Regular'
        prizes={numberList}
        prizeIndex={prizeIndex}
        spinningTime={10.1}
        start={start}
        onPrizeDefined={handlePrizeDefined}
        topChildren={<img className={styles.pin_top} src={ImgPinTop} alt='Pin top image'/>}
        bottomChildren={<img className={styles.pin_bottom} src={ImgPinBottom} alt='Pin bottom image'/>}
        options={{stopInCenter: true}}
        designOptions={{
          hideCenterDelimiter: true,
          withoutAnimation: true,
          prizeItemWidth: 80,
        }}
        prizeItemRenderFunction={(props, index) => (
          <li key={props.color + index}>
            <img className={styles.number_item}  src={props.img} width='74px' alt='Number image'/>
          </li>
        )}
      />
      <div className={styles.mask_right}></div>
    </div>
  )
}
export default RouletteSpinner
```

**Comment by ngdevc** [comment] 2022-07-06 15:06
### This is the delay bar.
![image](https://user-images.githubusercontent.com/65579678/177582815-5cbbd323-b1a2-4885-90a9-0d312ad607c6.png)

```
import React, { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import classNames from 'classnames';

import styles from './styles.module.scss'
import { AudioWaiting } from '../../../constants/audios'
import { AudioPlayer } from '../../Shared';
import { setIsRolling } from '../../../store/global'
import { getIsRolling } from '../../../store/global/selectors'

const DelayBar = ({hidden}) => {
  const dispatch = useDispatch();
  const isRolling = useSelector(getIsRolling);

  const [duration, setDuration] = useState(150);
  const [playing, setPlaying] = useState(false);

  useEffect(() => {
    if (duration >= 150) setPlaying(true);
    if (duration <= 0 && !isRolling) dispatch(setIsRolling(true));
  }, [duration])

  useEffect(() => {
    if (!isRolling) {
      setDuration(150);
      const interval = setInterval(() => {
        setDuration(prev => {
          if (prev < 0) clearInterval(interval) ;
          return prev - 0.5;
        });
      }, window.navigator.userAgent.indexOf('Firefox') !== -1 ? 46.999999999999996447285 : 50);
      return () => clearInterval(interval);
    }
  }, [isRolling])

  const getTitle = () => {
    return !hidden && isRolling 
      ? <>ROLLING ... <br /><span>You are participating in this round</span></>
      : `AUTO ROLL IN ${Math.floor(1 + duration/10)}s ...`;
  }

  return (
    <div 
      className={classNames('', {
        [styles.auto_roll_duration]: true,
        [styles.show]: duration > 0 || isRolling
      })}
    >
        <AudioPlayer src={AudioWaiting} playing={playing} onEnded={() => setPlaying(false)}/>
        <p className={classNames('mb-0 mt-0', {[styles.show]: !hidden})} >
            {getTitle()}
        </p>
        <progress 
          max="150" 
          value={duration}
          className={classNames('', {
            [styles.hidden]: duration <= 0
          })}
        >
        </progress>
    </div>
  )
}

export default DelayBar
```

**Comment by ngdevc** [comment] 2022-07-06 15:09
In the component **Delaybar**, if the duration length <= 0, set isRolling to true by `dispatch(setIsRolling(true))`, then the roulette will be started.
but If I inactive this tab before roulette is started and active this tab after roulette is started, direction moves in the opposite direction or moves slowly.

**Comment by ngdevc** [comment] 2022-07-06 15:09
@IvanAdmaers

**Comment by IvanAdmaers** [comment] 2022-07-06 15:45
Thank you. I’ll try to reproduce it

**Comment by ngdevc** [comment] 2022-07-06 16:53
thanks

**Comment by IvanAdmaers** [comment] 2022-07-07 07:12
Based your code I reproduced the roulette on CodeSandbox. I made minimal changes just to avoid of using Redux.

You can see it here - [https://codesandbox.io/s/rrp-github-issue-obdb93](https://codesandbox.io/s/rrp-github-issue-obdb93).

In my browser there are no problems with the roulette.

Can you please open it and to test is there your issue?

**Comment by ngdevc** [comment] 2022-07-07 15:14
Thx, let me check

**Comment by ngdevc** [comment] 2022-07-07 15:22
Is it related with the Redux? But I have to use Redux for the `isRolling`. 
Because It should be sync with backend.

**Comment by IvanAdmaers** [comment] 2022-07-07 15:25
Yes, sure. I don’t use Redux in that case just because  it’s a test

**Comment by IvanAdmaers** [comment] 2022-07-07 15:28
I added setTimeout 0 for useEffect that sets setStart(true) but I’m not sure it’s useful

**Comment by ngdevc** [comment] 2022-07-07 15:42
I tested it, but it's not useful. i mean setTimeout 0 for useEffect that sets setStart(true)

**Comment by IvanAdmaers** [comment] 2022-07-07 15:48
Could you reproduce the problem with roulette spinning to the opposite side in that Sandbox example?

**Comment by ngdevc** [comment] 2022-07-07 15:58
Let me check

**Comment by IvanAdmaers** [comment] 2022-07-18 06:06
Hi, @tortuc. If the issue is still actual let me know. Otherwise I'll close the issue. You'll be able to open new issues in future.

**Comment by ngdevc** [comment] 2022-07-19 02:41
@IvanAdmaers  the issue is still actual

**Comment by IvanAdmaers** [comment] 2022-07-19 05:48
I understand you but first we need to reproduce this issue. For example here - https://codesandbox.io/s/rrp-github-issue-obdb93.

**Comment by ngdevc** [comment] 2022-07-20 12:16
I'm not sure how redux make it to work wrong..

**Comment by IvanAdmaers** [comment] 2022-07-21 15:37
I can tell you exactly - your roulette component is correct. I reproduced and checked your code on sandbox. There is no any issues. You should focus on how do you set prize index.

If you’ll have any questions in future feel free to open a new issue. And it’d be amazing if you’ll have an opportunity to send a link to codesanbox with reproduced issue. It’ll help to solve an issue as quickly as possible.

**Closed as completed by IvanAdmaers** 2022-07-21 15:37 UTC
